### ISSUE TITLE
Date arithmetics

### ISSUE THREAD

**Issue by lakerka** [vitalets/babel-plugin-runtyper#11]
Some arithmetics on date object should be allowed without warning as shown in example here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

Currently getting warnings like:
`index.js:70 Error: Numeric operation with non-numeric value: "2018-05-04T12:18:52... (Date) - "2018-05-04T12:12:08... (Date)`

**Comment by vitalets** [comment]
For me personally explicit usage of `.valueOf` in that case looks more clear.
For example, when somebody see such line:
```js
date1 - date2
```
he can be confused with that result is? Days, hours, seconds, milliseconds?
When I explicitly write:
```js
date1.valueOf() - date2.valueOf()
```
it creates less cognitive payload imho.

**Comment by lakerka** [comment]
If we would talk about cognitive load I think that both cases are equally wrong. Your example with `valueOf` depends on assumption that you know what value of date actually means. In the same sense subtracting two dates depends on assumption that you know what the value of subtraction is. Problem would not exist if we would explicitly state what the result is like `(date1 - date2).seconds`.

Now what troubles me is not cognitive load but warnings that I get when I perform legit operations on builtin types. Since this is valid operation that does not involve type conversions or anything in that manner I think that there should be no warning. What do you think @vitalets ?

**Comment by vitalets** [comment]
I agree that cognitive load exists in both cases. Also it is rather personal.

> Since this is valid operation that does not involve type conversions or anything in that manner I think that there should be no warning.

This is not so. It involves silent type conversion, actually call of `valueOf()` method. The same can occur in the app with usual objects:
```js
var a = {valueOf: () => 3};
var b = {valueOf: () => 2};
// somewhere later...
console.log(a - b); // => 1
```
But for readers of code this is magic and can lead to potential bugs.
Looking at `a - b` I can think that `a` is number, but 
```js
typeof a // => "object"
```
Also thinking that it is a number I can do the following:
```
a++;
// now typeof a === "number"
```
and so on.

Imho overloaded operators and implicit conversions are always bad.
Subtracting dates for me is very similar to, for example, adding Arrays:
```js
[1,2,3] + [4,5,6] // => "1,2,34,5,6"
```
but so many magic here.

Although example with dates is mentioned on MDN, I don't think this is recommended.

**Comment by lakerka** [comment]
Agree.
