### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Semigradsky** [vitalets/babel-plugin-runtyper#5]
See https://github.com/vitalets/babel-plugin-runtyper/blob/3627294d3bf31e3a138aa518591ba1d492d2e297/src/utils.js#L38

It hapens in browser.

**Comment by Semigradsky** [comment]
Possible solution:
```js
var g = (typeof global === 'object' && global.global === global && global) || window;
```

**Comment by vitalets** [comment]
@Semigradsky thanks a lot! Will fix it.
