### ISSUE TITLE
implicitCompareNull and implicitCompareUndefined options do not work

### ISSUE THREAD

**Issue by zilvinasrudzionis** [vitalets/babel-plugin-runtyper#8]
Options described in documentation `implicitCompareNull`, `implicitCompareUndefined` which I would like to use do not work and cause: `Unknown Runtyper option name: ...`

**Comment by vitalets** [comment]
Hi @zilvinasrudzionis !
They are outdated options that were renamed to `implicitEqualNull` and `implicitEqualUndefined` respectively. I forgot to update one section in readme, thanks for pointing on that.
Feel free to reopen, if it does not help.

**Comment by zilvinasrudzionis** [comment]
Thanks @vitalets .
